#!/usr/bin/env python3
"""White-label brand configuration for Output Forge.

A single ``brand.json`` drives the look and the authorship of every artifact, so
an agency can ship the audit under its own name without touching code. The config
is small and fully optional: any field left out falls back to a neutral default,
so a run with no brand file still produces complete, unbranded output.

The loader validates the few fields that must be well formed (the colours must be
hex) and otherwise merges the file over the defaults. It also exposes a short,
stable fingerprint of the resolved brand, which the manifest records instead of an
absolute file path, so the run-state stays portable and deterministic.
"""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Any

# A neutral, unbranded default. Colours are a restrained, print-friendly palette.
DEFAULT_BRAND: dict[str, Any] = {
    "name": "Spektr",
    "tagline": "Offline keyword and demand intelligence",
    "author": "Spektr",
    "contact": "",
    "footer": "Generated by Spektr. Figures carry their own provenance.",
    "font_family": "Helvetica, Arial, sans-serif",
    "colors": {
        "primary": "#1f3a5f",
        "secondary": "#4a6fa5",
        "accent": "#c8772e",
        "text": "#1a1a1a",
        "muted": "#6b7280",
        "background": "#ffffff",
        "band": "#cdddec",
    },
    "logo": "",
}

# Keys under ``colors`` that must be valid hex if present.
_COLOR_KEYS = tuple(DEFAULT_BRAND["colors"].keys())

_HEX = re.compile(r"^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$")


class BrandError(Exception):
    """Raised when a brand file cannot be parsed or is malformed."""


def _validate_color(key: str, value: Any) -> str:
    if not isinstance(value, str) or not _HEX.match(value.strip()):
        raise BrandError(f"colors.{key} must be a hex colour like '#1f3a5f', got {value!r}")
    return value.strip().lower()


def resolve_brand(raw: dict[str, Any] | None) -> dict[str, Any]:
    """Merge a raw brand mapping over the defaults and validate it.

    ``raw`` may be ``None`` (use the defaults wholesale) or a partial mapping. Only
    string fields and the colour block are honoured; unknown keys are ignored so a
    richer file from a future version does not break an older reader.
    """
    brand = json.loads(json.dumps(DEFAULT_BRAND))  # deep copy without importing copy
    if raw is None:
        return brand
    if not isinstance(raw, dict):
        raise BrandError("brand config must be a JSON object")

    author_given = isinstance(raw.get("author"), str) and raw["author"].strip() != ""
    for field in ("name", "tagline", "author", "contact", "footer", "font_family", "logo"):
        if field in raw and raw[field] is not None:
            if not isinstance(raw[field], str):
                raise BrandError(f"brand.{field} must be a string")
            brand[field] = raw[field].strip()

    colors = raw.get("colors")
    if colors is not None:
        if not isinstance(colors, dict):
            raise BrandError("brand.colors must be an object")
        for key, value in colors.items():
            if key in _COLOR_KEYS:
                brand["colors"][key] = _validate_color(key, value)

    # The author follows the brand name unless the file set it explicitly, so a
    # custom brand never carries the default author into its documents.
    if not author_given:
        brand["author"] = brand["name"] or DEFAULT_BRAND["author"]
    return brand


def load_brand(path: Path | None) -> dict[str, Any]:
    """Load and validate a brand file, or return the defaults when ``path`` is None."""
    if path is None:
        return resolve_brand(None)
    try:
        data = json.loads(path.read_text(encoding="utf-8-sig"))
    except FileNotFoundError as exc:
        raise BrandError(f"brand file not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise BrandError(f"brand file is not valid JSON: {path}") from exc
    body = data.get("brand", data) if isinstance(data, dict) else data
    return resolve_brand(body)


def brand_fingerprint(brand: dict[str, Any]) -> str:
    """Return a short, stable hash of the resolved brand for the manifest.

    The manifest records this rather than the brand file path, so the run-state
    does not carry an absolute path and stays byte-stable across machines.
    """
    canonical = json.dumps(brand, ensure_ascii=False, sort_keys=True)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:12]
